package com.amrsamy.caseflow.application.service;

import com.amrsamy.caseflow.adapters.persistence.entity.CaseEntity;
import com.amrsamy.caseflow.domain.model.Priority;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.concurrent.ThreadLocalRandom;

@Service
public class DemoSimulationService {

    private static final String[] TITLES = {
            "Suspicious login spike",
            "Payment anomaly detected",
            "KYC document mismatch",
            "Device fingerprint collision",
            "Velocity rule breach",
            "Chargeback cluster",
            "Geo-impossible travel",
            "AML alert escalation"
    };

    private static final String[][] SKILL_SETS = {
            {"fraud"},
            {"aml"},
            {"kyc"},
            {"fraud", "aml"},
            {"payments"},
            {"kyc", "aml"},
            {}
    };

    private final CaseApplicationService caseApplicationService;

    public DemoSimulationService(CaseApplicationService caseApplicationService) {
        this.caseApplicationService = caseApplicationService;
    }

    public List<Long> simulate(Long tenantId, int count, Long actorId) {
        if (count < 1) {
            count = 1;
        }
        if (count > 1000) {
            count = 1000;
        }

        Priority[] priorities = Priority.values();
        List<Long> ids = new ArrayList<>(count);

        for (int i = 0; i < count; i++) {
            ThreadLocalRandom rnd = ThreadLocalRandom.current();
            Priority priority = priorities[rnd.nextInt(priorities.length)];
            String[] skills = SKILL_SETS[rnd.nextInt(SKILL_SETS.length)];
            String title = TITLES[rnd.nextInt(TITLES.length)] + " #" + (i + 1);

            CaseEntity created = caseApplicationService.ingestEvent(
                    tenantId,
                    "SIM-" + System.currentTimeMillis() + "-" + i,
                    title,
                    "Synthetic demo event generated by CaseFlow load simulator",
                    priority,
                    Set.copyOf(Arrays.asList(skills)),
                    actorId);

            caseApplicationService.enqueuePipeline(created.getId());
            ids.add(created.getId());
        }
        return ids;
    }
}
